d /etc/velyx 0755 root root -
d /var/lib/velyx 0755 root root -
d /var/log/velyx 0755 root root -
d /var/lib/velyx/users 0755 root root -
d /var/lib/velyx/users/velyx 0755 velyx velyx -
d /home/velyx 0755 velyx velyx -
d /home/velyx/.config 0755 velyx velyx -
d /home/velyx/.config/velyx 0755 velyx velyx -
d /home/velyx/.config/systemd 0755 velyx velyx -
d /home/velyx/.config/systemd/user 0755 velyx velyx -
d /home/velyx/.config/systemd/user/default.target.wants 0755 velyx velyx -
d /home/velyx/.local 0755 velyx velyx -
d /home/velyx/.local/state 0755 velyx velyx -
d /home/velyx/.local/state/velyx 0755 velyx velyx -
d /home/velyx/.velyx 0755 velyx velyx -
d /run/velyx 0755 root root -
d /run/velyx/session 0755 velyx velyx -
