use crate::model::{RiskLevel, ToolDefinition};

pub fn default_tools() -> Vec<ToolDefinition> {
    vec![
        ToolDefinition {
            id: "app.launch".to_string(),
            name: "Запуск приложения".to_string(),
            description: "Запускает приложение только через launcher-service.".to_string(),
            capability_group: "apps".to_string(),
            risk_level: RiskLevel::SafeWrite,
            requires_confirmation: false,
            required_permissions: vec![],
            input_schema: "app_id".to_string(),
            output_schema: "status, message".to_string(),
            downstream_service: "launcher-service".to_string(),
        },
        ToolDefinition {
            id: "settings.get".to_string(),
            name: "Чтение настройки".to_string(),
            description: "Читает настройку только через settings-service.".to_string(),
            capability_group: "settings".to_string(),
            risk_level: RiskLevel::SafeRead,
            requires_confirmation: false,
            required_permissions: vec![],
            input_schema: "key".to_string(),
            output_schema: "value".to_string(),
            downstream_service: "settings-service".to_string(),
        },
        ToolDefinition {
            id: "files.search".to_string(),
            name: "Поиск файлов".to_string(),
            description: "Ищет файлы только через metadata-only file-service.".to_string(),
            capability_group: "files".to_string(),
            risk_level: RiskLevel::SafeRead,
            requires_confirmation: false,
            required_permissions: vec![],
            input_schema: "mode, query".to_string(),
            output_schema: "results".to_string(),
            downstream_service: "file-service".to_string(),
        },
        ToolDefinition {
            id: "diagnostics.summary".to_string(),
            name: "Диагностическая сводка".to_string(),
            description: "Возвращает безопасную системную сводку через diagnostics-service.".to_string(),
            capability_group: "diagnostics".to_string(),
            risk_level: RiskLevel::SafeRead,
            requires_confirmation: false,
            required_permissions: vec![],
            input_schema: "scope".to_string(),
            output_schema: "summary".to_string(),
            downstream_service: "diagnostics-service".to_string(),
        },
        ToolDefinition {
            id: "permissions.update".to_string(),
            name: "Изменение разрешений".to_string(),
            description: "Меняет app permissions только через permissions-service.".to_string(),
            capability_group: "security".to_string(),
            risk_level: RiskLevel::SensitiveWrite,
            requires_confirmation: true,
            required_permissions: vec!["security_policy".to_string()],
            input_schema: "app_id, permission, decision".to_string(),
            output_schema: "status".to_string(),
            downstream_service: "permissions-service".to_string(),
        },
        ToolDefinition {
            id: "security.explain".to_string(),
            name: "Объяснение security-решения".to_string(),
            description: "Объясняет последнее security/system решение без side effects.".to_string(),
            capability_group: "security".to_string(),
            risk_level: RiskLevel::SafeRead,
            requires_confirmation: false,
            required_permissions: vec![],
            input_schema: "app_id".to_string(),
            output_schema: "summary, reason, source, suggested_action".to_string(),
            downstream_service: "explainability-layer".to_string(),
        },
    ]
}
